source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RBIDrawerViewController_Example', :exclusive => true do
  pod "RBIDrawerViewController", :path => "../"
end

target 'RBIDrawerViewController_Tests', :exclusive => true do
  pod "RBIDrawerViewController", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
