source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CYFDrawerViewController_Example', :exclusive => true do
  pod "CYFDrawerViewController", :path => "../"
end

target 'CYFDrawerViewController_Tests', :exclusive => true do
  pod "CYFDrawerViewController", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
